site_name: Kafkapy 
site_description: Python CLI for managing a kafka cluster 
site_url: ""
theme:
  name: material
  features:
    - content.code.annotate
  palette:
    primary: light blue
    accent: purple
  font:
    text: Poppins 
    code: Poppins 
  icon:
    repo: fontawesome/brands/git
repo_name: symonk/kafkapy
repo_url: https://github.com/symonk/kafkapy/
edit_uri: ""
extra_css:
 - stylesheets/extra.css
watch:
  - kafkapy 
nav:
    - Introduction: index.md
    - User Guide: user_guide.md
    - Topic Commands: topics.md

plugins:
    - search
    - mkdocstrings:
        default_handler: python
        handlers:
          python:
            options:
              heading_level: 2
              show_root_heading: true
              show_symbol_type_heading: true
              docstring_style: sphinx
              line_length: 120
              show_if_no_docstring: true
              merge_init_into_class: true
              show_source: true
              docstring_section_style: spacy
              show_bases: false
              show_symbol_type_toc: true
              annotations_path: brief
              show_signature_annotations: false
              separate_signature: true
              unwrap_annotated: true
              show_docstring_returns: true
              show_docstring_yields: true

markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
copyright: Copyright &copy; 2024 Simon Kerr
